version: '3.8'

services:

  mongodb:
    container_name: mongo
    image: mongo:7.0.0-jammy
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge